name: Build and package

env:
  OUTPUT_PATH: ${{ github.workspace }}/.output
  DOTNET_VERSION: "2.2.207"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Build with dotnet
      run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
    
    - name: Package functions
      uses: actions/upload-artifact@v1
      with:
        name: functions
        path: ${{ env.OUTPUT_PATH }}
